# Generated by Django 2.1 on 2020-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_name', models.TextField(blank=True, null=True)),
                ('n95_weekly_volume', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Hospitals',
            },
        ),
    ]
