# Generated by Django 2.1 on 2020-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('hospital_name', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('contact_persons', models.TextField(blank=True, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('weekly_supply', models.TextField(blank=True, null=True)),
                ('coveralls_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('n95_masks_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('surgical_mask_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('fluid_resistant_protective_gown_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('sterile_gloves_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('face_shield_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('booties/shoe_cover_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('goggles_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('hair_caps_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('alcohol_70%_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('disinfectants_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('aerosol_(acrylic)_box_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('personnel_count_for_food', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('submitted_by', models.TextField(blank=True, null=True)),
                ('number_of_active_cases', models.IntegerField(blank=True, null=True)),
                ('your_designation', models.TextField(blank=True, null=True)),
                ('department_(optional)', models.TextField(blank=True, null=True)),
                ('how_long_will_current_supplies_last?', models.TextField(blank=True, null=True)),
                ('other_supplies_needed', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hospital_id_of_submitting_person', models.TextField(blank=True, null=True)),
                ('acceptance', models.TextField(blank=True, null=True)),
                ('update_data', models.TextField(blank=True, null=True)),
                ('ppe_modified', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('last_updated', models.TextField(blank=True, null=True)),
                ('with_needs?', models.TextField(blank=True, null=True)),
                ('date_submitted', models.TextField(blank=True, null=True)),
                ('check', models.TextField(blank=True, null=True)),
                ('last_updated_by_hospital', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Hospitals',
            },
        ),
    ]
