# Generated by Django 2.1 on 2020-03-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='alcohol_70_weekly_volume',
            new_name='alcohol_70_weekly_volume',
        ),
    ]
