# Generated by Django 2.1 on 2020-04-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200331_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillments',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('donated_by', models.TextField(blank=True, null=True)),
                ('date_fulfilled', models.TextField(blank=True, null=True)),
                ('reported_by', models.TextField(blank=True, null=True)),
                ('ppe_kits_provided', models.IntegerField(blank=True, null=True)),
                ('n95_masks_provided', models.IntegerField(blank=True, null=True)),
                ('surgical_masks_provided', models.IntegerField(blank=True, null=True)),
                ('fluid_resistant_protective_gowns_provided', models.IntegerField(blank=True, null=True)),
                ('sterile_gloves_provided', models.IntegerField(blank=True, null=True)),
                ('face_shields_provided', models.IntegerField(blank=True, null=True)),
                ('booties/shoe_cover_provided', models.IntegerField(blank=True, null=True)),
                ('goggles_provided', models.IntegerField(blank=True, null=True)),
                ('hair_caps_provided', models.IntegerField(blank=True, null=True)),
                ('alcohol_70_provided', models.IntegerField(blank=True, null=True)),
                ('disinfectants_provided', models.IntegerField(blank=True, null=True)),
                ('aerosol_(acrylic)_box_provided', models.IntegerField(blank=True, null=True)),
                ('food_provided', models.IntegerField(blank=True, null=True)),
                ('your_contact_details', models.TextField(blank=True, null=True)),
                ('donation_status', models.TextField(blank=True, null=True)),
                ('field_22', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Fulfillments',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('covered_week', models.IntegerField(blank=True, null=True)),
                ('request_status', models.IntegerField(blank=True, null=True)),
                ('deadline', models.IntegerField(blank=True, null=True)),
                ('overdue', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('date_submitted', models.TextField(blank=True, null=True)),
                ('how_long_will_your_current_supplies_last', models.TextField(blank=True, null=True)),
                ('coveralls_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('n95_masks_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('surgical_mask_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('fluid_resistant_protective_gown_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('sterile_gloves_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('face_shield_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('booties/shoe_cover_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('goggles_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('hair_caps_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('alcohol_70_weekly_volume_(gallons)', models.IntegerField(blank=True, null=True)),
                ('disinfectants_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('aerosol_(acrylic)_box_weekly_volume', models.IntegerField(blank=True, null=True)),
                ('average_personnel_count', models.IntegerField(blank=True, null=True)),
                ('your_name', models.TextField(blank=True, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('your_designation', models.TextField(blank=True, null=True)),
                ('your_contact_details', models.TextField(blank=True, null=True)),
                ('done_updated', models.TextField(blank=True, null=True)),
                ('number_of_active_cases', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Updates',
            },
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='how_long_will_current_supplies_last?',
            new_name='how_long_will_current_supplies_last',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='with_needs?',
            new_name='last_updated_(by_hospital)',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='with_needs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hospitals'),
        ),
        migrations.AddField(
            model_name='requests',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hospitals'),
        ),
        migrations.AddField(
            model_name='fulfillments',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Requests'),
        ),
    ]
