# Generated by Django 2.1 on 2020-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200402_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='covered_week',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='deadline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='overdue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
